accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # 회원 가입 path
    path('login/', views.signin, name='signin'), # 로그인 path
    path('logout/', views.signout, name='signout'), # 로그아웃 path
    path('<username>/', views.profile, name='profile'), # 프로필 path
    path('<username>/follow', views.follow, name='follow'), # 추가기능) 팔로우 path
    
]

hoIT/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

#from articles import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

accounts/models.py
from django.db import models
# 장고 AbstractUser 모델에 필요한 필수 필드는 username, password
from django.contrib.auth.models import AbstractUser
from django.conf import settings


# Create your models here.
# 관리자 호환 권한의 장고 AbstractUser 모델 상속
class User(AbstractUser):  
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings') # 추가 기능입니다 M:N 팔로워 기능

articles/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from .models import User
# 유저 등록 및 암호 생성을 위한 필드 및 유효성 검사를 제공 폼 클래스
from django.contrib.auth.forms import UserCreationForm
# 유저 인증을 위한 필드 및 유효성 검사 제공 폼 클래스
from django.contrib.auth.forms import AuthenticationForm


# 유저 생성 폼. UserCreationForm 상속.
class myUserCreationForm(UserCreationForm):
    # 폼 클래스 생성자 정의
    def __init__(self, *args, **kwargs):
        # 폼 초기화 및 슈퍼 클래스 생성자 호출
        super().__init__(*args,**kwargs)
        # 추가된 속성으로 업데이트할 필드 이름 목록
        class_update_fields = ['username', 'password1', 'password2']
        # class_update_fields 리스트 돌면서
        for field_name in class_update_fields:
            # css class form-control로 각 폼 필드의 widget.attrs dict 업데이트.
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })
    # 폼에서 메타 데이터 구성을 위해 중첩되는 클래스 정의
    class Meta:
        # 폼에 사용할 모델 지정
        model = User
        # 폼에 포함할 필드 지정. 유효성 검사에 필드 사용
        fields = ['username', 'password1', 'password2']

# 유저 인증 폼. AuthenticationForm 상속.
class myAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username','password']

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login, logout, get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import *

# Create your views here.

## 회원 가입 뷰
def signup(request):
    # 로그인한 사용자는 회원 가입 템플릿 액세스 제한
    if request.user.is_authenticated:
        # 피드 템플릿:view 연결
        return redirect('피드:view')
    # 회원 가입 폼이 제출 되었다면
    if request.method == 'POST': 
        # 회원 가입 폼 = 인스턴스 생성에 필요한 필드 데이터 제출 요청
        signupform = myUserCreationForm(request.POST)
        # 회원 가입 폼 유효성 검사 Form.is_valid()
        if signupform.is_valid():
            # 회원 가입 데이터 저장
            signupform.save()
            # 피드 템플릿:view 연결
            return redirect('피드:view')
    # 폼이 유효하지 않거나 요청 메서드가 POST가 아니면
    else:
        # 데이터가 없는 회원 가입 폼 인스턴스 생성
        signupform = myUserCreationForm()
    # 'form'이름으로 매핑된 유효하지 않은 데이터 필드 context를 렌더링
    context = {
        'form': signupform,
    }# 다시 회원 가입 템플릿 반환, context 출력
    return render(request, 'accounts/signup.html', context)

## 로그인 뷰
def signin(request):
    if request.user.is_authenticated:
        # 피드 템플릿:view 연결
        return redirect('피드:view')
    # 로그인 폼이 요청되면
    if request.method == 'POST':
        # 인증 요청, 유효성 검사를 위한 인스턴스 생성
        form = myAuthenticationForm(request, request.POST)
        
        if form.is_valid():
            # 양식이 유효한 경우 사용자는 제출된 폼 데이터와 연관된 사용자를 로그인시킵니다.
            login(request, form.get_user())
            # 피드 템플릿:view 연결
            return redirect('피드:view')
    # 폼이 유효하지 않거나 요청 메서드가 POST가 아니면
    else:
        # 데이터가 없는 로그인 폼 인스턴스 생성
        form = myAuthenticationForm()
    # 'form'이름으로 매핑된 유효하지 않은 데이터 필드 context를 렌더링
    context = {
        'form': form,
    }  # 다시 로그인 템플릿 반환, context 출력
    return render(request, 'accounts/login.html', context)

## 로그 아웃 뷰
# 로그인 인증된 유저만 엑세스
@login_required
def signout(request):
    # 로그인 인증된 요청 객체와 관련있는 인증된 유저의 세션을 로그아웃합니다.
    logout(request)
    return redirect('피드:view')

# 프로필 뷰


@login_required
def profile(request, username):
    # 프로젝트에 활성화된 유저 모델을 검색하고 반환
    
    User = get_user_model()
    # 주어진 개체 username이 존재하지 않는다면 404 error 반환
    profile_owner = get_object_or_404(User, username=username)
    # 검색된 유저 인스턴스를 값으로 저장합니다.
    context = {
        'profile_owner': profile_owner
    }
    return render(request, 'accounts/profile.html', context)

""" def test(request):
    username = request.user.is_authenticated
    print(username)
    profile(request, username) """



## 추가 기능입니다 팔로우/팔로워 뷰
def follow(request, username):
    User = get_user_model()
    writer = get_object_or_404(User, username=username)
    # 현재 로그인 중인 요청 객체로부터 관련된 유저를 검색합니다
    user = request.user
    # 작성자가 현재 로그인 요청 유저와 다른지 확인
    if writer != user:
        # 현재 로그인 중인 유저 pk가 팔로워 목록에 있는지 
        # 유저 모델 필드를 검색하고 User 모델 필드를 쿼리해서 
        # 작성자를 팔로우하고 있는지 확인
        if writer.followers.filter(pk=user.pk).exists():
            # 현재 로그인 중인 유저가 writer 팔로우 중이면 writer 팔로워 목록에서 유저 제거
            writer.followers.remove(user)
        else:
            # 팔로우 하고있지 않으면 팔로워 추가
            writer.followers.add(user)
    # 업데이트된 팔로워 목록이 반영된 유저 프로필 페이지로 리디렉션
    return redirect('accounts:profile', username)

articles/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/index.html
<!-- {% extends 'base.html' %}
{% block content %}
    {% for  in  %}
        <a href="{% url ':' .pk %}">{{ .title }}</p>
        <hr>
    {% endfor %}
{% endblock %} -->

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <div class="d-flex justify-content-end">
        <button class="btn btn-info">LOGIN</button>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ profile_owner }}님의 프로필 페이지.</h1>
    <hr>
    <p>팔로잉: {{ profile_owner.followings.all|length }}</p>
    <p>팔로워: {{ profile_owner.followers.all|length }}</p>
    {% if request.user != profile_owner %}
        {% if request.user in profile_owner.followers.all %}
        <a href="{% url 'accounts:follow' profile_owner %}">UNFOLLOW</a>
        {% else %}
        <a href="{% url 'accounts:follow' profile_owner %}">FOLLOW</a>
        {% endif %}
    {% endif %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-success text-light">SIGNUP</button>
    </div>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django-PJT4</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/b4971aab15.js" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <a class="navbar-brand" href="/">PJT4</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    {% comment %} <a class="nav-link" href="{% url '앱:view' %}">Movie</a> {% endcomment %}
                </li>

                {% if user.is_authenticated %}<!-- login 된 상태일 경우 -->
                <a href="{% url 'accounts:profile' user.username %}" class="p-2 text-light">{{ user.username }}님
                    환영합니다.</a>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sign out
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'accounts:signout' %}">Sign Out</a>
                        </div>
                        {% else %}
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Sign Up / Sign In
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a>
                                    <a type="button" class="dropdown-item" data-toggle="modal" data-target="#SIGNIN">
                                        Sign In
                                    </a>
                                </div>
                            </li>
                            {% endif %}
                        </ul>
        </div>
    </nav>
    {% include 'login.html' %}
    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SIGN IN</title>
</head>

<body>
    <!-- Modal -->
    <div class="modal fade" id="SIGNIN" tabindex="-1" role="dialog" aria-labelledby="SIGNINTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="SIGNINTitle">SIGN IN</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'accounts:signin' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row mb-3 mt-2">
                            <div class="col-12">
                                {% if error %}
                                <div class="d-flex flex-row">
                                    <label for="username" class="mr-3">Username</label>
                                    <p class="text-danger p-0 m-0">{{ error }}</p>
                                </div>
                                {% else %}
                                <label for="username">Username</label>
                                {% endif %}
                                <div><input type='text' id='username' name="username" class="form-control"></div>
                            </div>
                        </div>
                        <div class="form-row mb-6">
                            <div class="col-12">
                                <label for="password">Password</label>
                                <div><input type='password' id='password' name="password" class="form-control"></div>
                            </div>
                        </div>
                        <div class="modal-footer mt-5">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Sign In</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


</body>

</html>